[project]
name = "test-environment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.1.0",
    "pandas>=3.0.0",
    "supabase>=2.27.2",
]
